export const FETCH_VIEW_PRODUCTS_REQUEST = "FETCH_VIEW_PRODUCTS_REQUEST";
export const FETCH_VIEW_PRODUCTS_SUCCESS = "FETCH_VIEW_PRODUCTS_SUCCESS";
export const FETCH_VIEW_PRODUCTS_FAILURE = "FETCH_VIEW_PRODUCTS_FAILURE";
export const SET_SORT_BY = "SET_SORT_BY";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const TOGGLE_DISPLAY_CARD2 = "TOGGLE_DISPLAY_CARD2";
export const SET_SORTED_PRODUCTS = " SET_SORTED_PRODUCTS,";
